#ifndef OBJEKTINIO_PROGRAMAVIMO_UZDUOTIS_TESTING_H
#define OBJEKTINIO_PROGRAMAVIMO_UZDUOTIS_TESTING_H

void testDivision();

void generateNewFiles();

void testDivisionStrategies();

#endif  // OBJEKTINIO_PROGRAMAVIMO_UZDUOTIS_TESTING_H
